---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add mongo apt key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927

    - name: Add mongo repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse

    - name: Install package
      apt:
        name: mongodb-org
        update_cache: yes

    - name: Start and enable mongod service
      systemd:
        name: mongod
        state: started
        enabled: yes
