version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - front-net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - back-net
      - front-net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - back-net
      - front-net

volumes:
  post_db:

networks:
  back-net:
  front-net:
